### ISSUE TITLE
Unable to get HR in paper

### ISSUE THREAD

**Issue by icyhearts** [yaodi833/serm#2]
Thanks for your research work and releasing code.
I modified part of your code and made it able to run under python3.
Given hyper-parameter  in config.py, after running train.py, the best result I got is(On NY dataset):
```
[HR@1, HR@5, HR@10, HR@15, HR@20, distance]
=
[0.1710261569416499, 0.35412474849094566, 0.4607645875251509, 0.5130784708249497, 0.5513078470824949, 1921.2714494527042]
```
In your paper, on NY dataset, [HR@1 HR@5 HR@10 HR@20]=[0.2535 0.4507 0.5433 0.6237]
My running result is much worse than the result in paper.
Any suggestions on the different result?
Many thanks!

**Comment by yaodi833** [comment]
Please try the codes in the related zip file.
